contact_link_list=[['Acquia, Inc', 'https://www.acquia.com/about-us/contact'],
['Acquire Media', 'http://acquiremedia.com/contactus/'],
['Acrolinx GmbH', 'https://www.acrolinx.com/contact/'],
["Actian Corp.","https://www.actian.com/company/#locations"],
['Act-On Software', 'https://act-on.com/contact-us/'],
['Apple, Inc.', 'https://www.apple.com/contact/'],
['Aptara, Inc.', 'https://www.aptaracorp.com/about-aptara/contact-us'],
['Aquafadas', 'https://www.aquafadas.com/contact-us/'],
['Aria Systems, Inc.', 'https://www.ariasystems.com/contact-us/'], 
['Atex', 'https://www.atex.com/atex/contact-us/'],
['Atypon Systems, Inc.', 'https://www.atypon.com/about-us/locations/'],
['Automattic, Inc.', 'https://automattic.com/contact/'],
['Brightcove, Inc.', 'http://brightcove.com/en/contact-us'],
['COGNITIVESCALE', 'http://cognitivescale.com/contact/'],
['Cision US, Inc.', 'https://www.cision.com/us/about/media-kit/'],
['Clarabridge', 'https://www.clarabridge.com/contact/'],
['Cloudera, Inc.', 'http://cloudera.com/about/locations.html'],
['Cloudwords, Inc.', 'https://www.cloudwords.com/contactus'],
['Connotate', 'https://www.import.io/contact-sales/?utm_source=tate&utm_medium=website&utm_term=choose-contact-sales'],
['CoreMedia AG', 'https://www.coremedia.com/en/about/contact'],
['Crafter Software Corp.', 'http://craftersoftware.com/about/contact'],
['Crownpeak Technology', 'http://crownpeak.com/about/contact-us'],
['DNN Corp.', 'https://www.dnnsoftware.com/about/contact-dnn'],
['EBSCO Industries, Inc.', 'http://ebsco.com/about/offices'],
['Ephox', 'https://www.tiny.cloud/contact'],
['Episerver', 'http://episerver.com/contact-us'],
['Evergage, Inc.', 'https://www.evergage.com/contact-us/'],
['Facebook', 'http://facebook.com/about/privacy/update'],
['Hippo B.V.', 'https://www.bloomreach.com/en/about/terms-of-use'],
["Hootsuite Media, Inc.","https://hootsuite.com/about/contact-us"],
["Impelsys","https://www.impelsys.com/contact-us/"],
["Influitive","https://influitive.com/contact-us/"],
["Kenshoo Ltd","https://kenshoo.com/office-locations/"],
['Kentico Software', 'http://kentico.com/contact'],
['MadCap Software, Inc.', 'https://www.madcapsoftware.com/contact-us/'],
["MarkLogic Corp.","https://www.marklogic.com/locations/"],
['NewsCred', 'http://newscred.com/contact'],
["The Nielsen Co.","https://www.nielsen.com/in/en/contact-us/"],
['OneSpot', 'https://www.onespot.com/contact/'],
['OpenText Corp.', 'https://www.opentext.com/about/office-locations'],
["Oracle","http://oracle.com/corporate/contact/"],
['ProQuest, LLC', 'http://proquest.com/about/locations'],
['Quark Software, Inc.', 'https://www.quark.com/about/offices/'],
['Realview', 'http://realviewdigital.com/contact-us/'],
["Reprints Desk, Inc.","https://info.reprintsdesk.com/about/contact"],
["Salesforce.com, Inc.","https://www.salesforce.com/in/company/locations/"],
['SAP', 'https://www.sap.com/about/legal/impressum.html'],
['SAS Institute, Inc.', 'https://www.sap.com/about/legal/copyright.html'],
['SYSOMOS', 'http://sysomos.com/contact/'],
['Sitecore Corp. AS', 'http://sitecore.net/company/contact-us'],
['Siteworx, LLC', 'https://www.shift7digital.com/about-us/'],
['Sizmek, Inc.', 'https://www.sizmek.com/about/'],
['Skyword, Inc.', 'https://www.skyword.com/contact-us/'],
['Smartling, Inc.', 'http://smartling.com/contact-us'], 
['Splunk, Inc.', 'http://splunk.com/en_us/about-splunk/contact-us.html'],
['Spotify AB', 'https://www.spotify.com/in/about-us/contact/'],
['Syncfusion, Inc.','http://syncfusion.com/company/contact-us'],
["TapClicks","https://tapclicks.com/contact-us/"],
['Translations.com (A TransPerfect Co.)', 'http://translations.com/about/global-group'],
['Uberflip', 'https://www.uberflip.com/contact/'],
['Viglink', 'https://www.sovrn.com/contact/'],
['Webtrends', 'https://www.webtrends.com/about-us/contact-us/'],
['Wochit', 'https://www.wochit.com/contact/'],
['ZUMOBI', 'http://zumobi.com/contact/'],
['Zoomin', 'https://www.zoominsoftware.com/contact-us/'],
['welocalize', 'http://welocalize.com/contact/']]